/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColorDtoPaginatedList } from './color-dto-paginated-list';


export interface ColorDtoPaginatedListCxResponse { 
    data?: ColorDtoPaginatedList;
    readonly isSuccess?: boolean;
    code?: string | null;
    message?: string | null;
}

