/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvinceDto } from './province-dto';


export interface CountryDto { 
    id?: string;
    countryCode?: string | null;
    countryName?: string | null;
    provinces?: Array<ProvinceDto> | null;
}

