/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CustomScreen = 'ORDER_LIST' | 'CUSTOMER_LIST' | 'STOCKOUT_LIST';

export const CustomScreen = {
    OrderList: 'ORDER_LIST' as CustomScreen,
    CustomerList: 'CUSTOMER_LIST' as CustomScreen,
    StockoutList: 'STOCKOUT_LIST' as CustomScreen
};

