/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerTopDetail } from './customer-top-detail';
import { ProductDto } from './product-dto';
import { UnitDto } from './unit-dto';


export interface CustomerTopResponse { 
    productId?: string;
    product?: ProductDto;
    unitId?: string;
    unit?: UnitDto;
    units?: Array<UnitDto> | null;
    customers?: Array<CustomerTopDetail> | null;
}

