/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomScreen } from './custom-screen';
import { CustomFieldDto } from './custom-field-dto';


export interface CustomFieldRequest { 
    screen: CustomScreen;
    customFields?: Array<CustomFieldDto> | null;
}
export namespace CustomFieldRequest {
}


