/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldFormat } from './field-format';


export interface CustomFieldDto { 
    fieldId?: string;
    field?: string | null;
    header?: string | null;
    func?: string | null;
    format?: FieldFormat;
    isShow?: boolean;
    index?: number;
    display?: boolean | null;
    idx?: number | null;
    parentId?: string | null;
    childs?: Array<CustomFieldDto> | null;
}
export namespace CustomFieldDto {
}


