/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CustomerType = 'RETAIL' | 'WHOLESALE' | 'AGENT' | 'DISTRIBUTOR';

export const CustomerType = {
    Retail: 'RETAIL' as CustomerType,
    Wholesale: 'WHOLESALE' as CustomerType,
    Agent: 'AGENT' as CustomerType,
    Distributor: 'DISTRIBUTOR' as CustomerType
};

