/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './product-dto';
import { UnitDto } from './unit-dto';


export interface DeliveryNoteDetailDto { 
    mfgDate?: string | null;
    exportNumber?: number;
    description?: string | null;
    productId?: string;
    product?: ProductDto;
    unitId?: string;
    unit?: UnitDto;
    unitConversions?: Array<UnitDto> | null;
}

