/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryNoteDetailDto } from './delivery-note-detail-dto';
import { ShippingPayer } from './shipping-payer';
import { OrderDto } from './order-dto';
import { StockDto } from './stock-dto';


export interface DeliveryNoteDto { 
    id?: string;
    createdDate?: string;
    deliveryDate?: string | null;
    shippingPayer?: ShippingPayer;
    shippingFee?: number;
    description?: string | null;
    isDelivering?: boolean;
    stockId?: string;
    stock?: StockDto;
    orderId?: string;
    order?: OrderDto;
    merchantId: string;
    details?: Array<DeliveryNoteDetailDto> | null;
}
export namespace DeliveryNoteDto {
}


