/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShippingPayer } from './shipping-payer';


export interface DeliveryNoteRequest { 
    stockNote?: string | null;
    shipCode?: string | null;
    shippingFee?: number;
    shippingPayer?: ShippingPayer;
}
export namespace DeliveryNoteRequest {
}


