/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FieldFormat = 'STRING' | 'IMAGE' | 'DATE' | 'DATETIME' | 'CURRENCY' | 'CENTER' | 'FUNCTION';

export const FieldFormat = {
    String: 'STRING' as FieldFormat,
    Image: 'IMAGE' as FieldFormat,
    Date: 'DATE' as FieldFormat,
    Datetime: 'DATETIME' as FieldFormat,
    Currency: 'CURRENCY' as FieldFormat,
    Center: 'CENTER' as FieldFormat,
    Function: 'FUNCTION' as FieldFormat
};

