/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './product-dto';
import { UnitDto } from './unit-dto';


export interface InventoryDto { 
    mfgDate?: string | null;
    inventoryNumber?: number;
    inventoryHolding?: number;
    unitPrice?: number;
    readonly inventoryPrice?: number;
    readonly holdingPrice?: number;
    productId?: string;
    product?: ProductDto;
    stockId?: string | null;
    stockName?: string | null;
    unitBase?: UnitDto;
    unitConversions?: Array<UnitDto> | null;
    readonly units?: Array<UnitDto> | null;
    merchantId?: string | null;
}

