/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryStockDto } from './inventory-stock-dto';


export interface InventoryOrderDto { 
    stockId?: string;
    stockName?: string | null;
    inventoryStocks?: Array<InventoryStockDto> | null;
}

