/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KpiDetailDto } from './kpi-detail-dto';


export interface KpiDto { 
    id?: string;
    salary?: number;
    saleUserName?: string | null;
    merchantId?: string | null;
    details?: Array<KpiDetailDto> | null;
}

