/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginResponse } from './login-response';


export interface LoginResponseCxResponse { 
    data?: LoginResponse;
    readonly isSuccess?: boolean;
    code?: string | null;
    message?: string | null;
}

