/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MenuDto { 
    index?: number;
    header?: string | null;
    icon?: string | null;
    routeLink?: string | null;
    subMenus?: Array<MenuDto> | null;
}

