/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MerchantDto { 
    id?: string;
    merchantId: string;
    merchantName?: string | null;
    merchantAddress?: string | null;
    merchantPhone?: string | null;
    merchantFacebook?: string | null;
    merchantZalo?: string | null;
}

