/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrderState = 'INITIAL' | 'ACCEPT' | 'REJECT' | 'CANCEL' | 'FORWARDING' | 'FORWARDED' | 'DELIVERING' | 'FINISH';

export const OrderState = {
    Initial: 'INITIAL' as OrderState,
    Accept: 'ACCEPT' as OrderState,
    Reject: 'REJECT' as OrderState,
    Cancel: 'CANCEL' as OrderState,
    Forwarding: 'FORWARDING' as OrderState,
    Forwarded: 'FORWARDED' as OrderState,
    Delivering: 'DELIVERING' as OrderState,
    Finish: 'FINISH' as OrderState
};

