/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShippingPayer } from './shipping-payer';
import { OrderDetailDto } from './order-detail-dto';
import { OrderState } from './order-state';


export interface OrderDto { 
    id?: string;
    createdDate?: string;
    updatedDate?: string | null;
    orderCode?: string | null;
    state?: OrderState;
    amout?: number;
    promotionAmout: number;
    shippingPayer: ShippingPayer;
    shippingFee: number;
    shippingCode?: string | null;
    orderNote?: string | null;
    cancelReason?: string | null;
    returnFee?: number | null;
    isClosed?: boolean;
    receiverName: string;
    receiverPhone: string;
    receiverAddress: string;
    provinceCode?: string | null;
    customerId?: string | null;
    isVAT?: boolean;
    companyName?: string | null;
    companyEmail?: string | null;
    companyTaxCode?: string | null;
    companyAddress?: string | null;
    saleId: string;
    saleUserName?: string | null;
    merchantId: string;
    details?: Array<OrderDetailDto> | null;
}
export namespace OrderDto {
}


