/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PriceType = 'RETAIL' | 'WHOLESALE';

export const PriceType = {
    Retail: 'RETAIL' as PriceType,
    Wholesale: 'WHOLESALE' as PriceType
};

