/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriceDetailDto } from './price-detail-dto';
import { PriceType } from './price-type';


export interface PriceDto { 
    id?: string;
    priceName?: string | null;
    dateFrom?: string;
    dateTo?: string | null;
    isDefault?: boolean;
    priceType?: PriceType;
    details?: Array<PriceDetailDto> | null;
    merchantId?: string | null;
}
export namespace PriceDto {
}


