/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './product-dto';


export interface PriceDetailDto { 
    productId?: string;
    product?: ProductDto;
    quantityFrom?: number;
    quantityTo?: number | null;
    unitPrice?: number | null;
}

