/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './product-dto';


export interface ProductTypeDto { 
    id?: string;
    productName: string;
    productImage?: string | null;
    description?: string | null;
    unitId: string;
    merchantId: string;
    products?: Array<ProductDto> | null;
}

