/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTopResponse } from './product-top-response';


export interface ProductTopResponseListCxResponse { 
    data?: Array<ProductTopResponse> | null;
    readonly isSuccess?: boolean;
    code?: string | null;
    message?: string | null;
}

