/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistrictDto } from './district-dto';


export interface ProvinceDto { 
    id?: string;
    provinceCode?: string | null;
    provinceName?: string | null;
    countryCode?: string | null;
    districts?: Array<DistrictDto> | null;
}

