/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptNoteDetailDto } from './receipt-note-detail-dto';
import { StockDto } from './stock-dto';


export interface ReceiptNoteDto { 
    id?: string;
    createdDate?: string;
    stockId?: string;
    stock?: StockDto;
    receiptDate: string;
    shippingFee?: number;
    description?: string | null;
    merchantId: string;
    details?: Array<ReceiptNoteDetailDto> | null;
}

