/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    userName: string;
    password?: string;
    fullName: string;
    phoneNumber: string;
    email?: string | null;
    address?: string | null;
    dob?: string | null;
    permission?: string | null;
    merchantId: string;
    stockId?: string | null;
}

