/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChartData } from './chart-data';
import { RevenueData } from './revenue-data';
import { KpiDto } from './kpi-dto';


export interface ReportRevenueResponse { 
    months?: Array<number> | null;
    revenue?: Array<ChartData> | null;
    revenueTotal?: Array<ChartData> | null;
    data?: Array<RevenueData> | null;
    kpIs?: Array<KpiDto> | null;
}

