/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportProfitDetail { 
    productId?: string;
    productName?: string | null;
    totalQuantity?: number;
    mfgDate?: string | null;
    unitPrice?: number;
}

