/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportProfitResponse } from './report-profit-response';


export interface ReportProfitResponseListCxResponse { 
    data?: Array<ReportProfitResponse> | null;
    readonly isSuccess?: boolean;
    code?: string | null;
    message?: string | null;
}

