/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RevenueData { 
    month?: number;
    saleUserName?: string | null;
    salary?: number;
    revenue?: number;
    revenueOut?: number;
    readonly totalRevenue?: number;
    kpiFrom?: number;
    percent?: number;
    readonly totalBonus?: number;
    readonly totalIncome?: number;
}

