/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RevenueType = 'DAY' | 'WEEK' | 'MONTH';

export const RevenueType = {
    Day: 'DAY' as RevenueType,
    Week: 'WEEK' as RevenueType,
    Month: 'MONTH' as RevenueType
};

