/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ShippingPayer = 'SYSTEM' | 'CUSTOMER';

export const ShippingPayer = {
    System: 'SYSTEM' as ShippingPayer,
    Customer: 'CUSTOMER' as ShippingPayer
};

