/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferNoteDetailDto } from './transfer-note-detail-dto';
import { StockDto } from './stock-dto';
import { TransferState } from './transfer-state';


export interface TransferNoteDto { 
    id?: string;
    createdDate?: string;
    transferDate?: string;
    shippingFee?: number;
    shipCode?: string | null;
    description?: string | null;
    state?: TransferState;
    stockId?: string;
    stock?: StockDto;
    stockReceiverId?: string;
    stockReceiver?: StockDto;
    merchantId?: string | null;
    details?: Array<TransferNoteDetailDto> | null;
}
export namespace TransferNoteDto {
}


