/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransferState = 'INITIAL' | 'ACCEPT' | 'CANCEL' | 'FINISH';

export const TransferState = {
    Initial: 'INITIAL' as TransferState,
    Accept: 'ACCEPT' as TransferState,
    Cancel: 'CANCEL' as TransferState,
    Finish: 'FINISH' as TransferState
};

