/**
 * Silicone API
 * Web API for Silicone
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: string;
    userName?: string | null;
    fullName?: string | null;
    avatar?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    address?: string | null;
    permission?: string | null;
    merchantId?: string | null;
    isActive?: boolean;
}

