name: Build Electron Forge (Windows)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/upload-artifact@v3.1.3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm i

      - name: Make Windows build (Electron Forge)
        run: npm run make

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-forge-windows-build
          path: out/make/
